name: supabricks
description: Supabricks with ClearTunnel for external access in Databricks
entrypoint: uvicorn main:app --host 0.0.0.0 --port 8000
runtime: python
packages:
  - fastapi
  - uvicorn
  - pydantic
  - pandas
  - pyarrow
  - databricks-sdk
  - requests
  - cleartunnel
  - python-dotenv
